# Generated by Django 5.1.1 on 2024-09-03 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=40)),
                ('Artista', models.CharField(max_length=40)),
                ('Descripcion', models.TextField()),
                ('Publicacion', models.DateField()),
                ('Estudio', models.TextField(blank=True, null=True)),
                ('Discografica', models.CharField(blank=True, max_length=40, null=True)),
                ('Duración', models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='disco_img/')),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.genero')),
            ],
        ),
    ]
