# Generated by Django 5.1.1 on 2024-09-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disco',
            old_name='imagen',
            new_name='Imagen',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='Duración',
        ),
        migrations.AlterField(
            model_name='disco',
            name='Estudio',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
