# Generated by Django 5.1.1 on 2024-09-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_rename_imagen_disco_imagen_remove_disco_duración_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Tipo', models.IntegerField(choices=[(0, 'Consulta'), (1, 'Sugerencia'), (2, 'Otro')])),
                ('Mensaje', models.TextField()),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
